### ISSUE TITLE
Q: Is "Coroutine has been cancelled." an error message? How should one avoid it?

### ISSUE THREAD

**Issue by nathanfranke** [Shynixn/MCCoroutine#54]
This code prints `Coroutine has been cancelled.` after a second.
```kt
val job = launch { // Plugin.launch
	delay(1000.seconds)
}
launch { // Plugin.launch
	delay(1.seconds)
	job.cancel()
}
```

However, this code does not.
```kt
launch { // Plugin.launch
	val job = launch { // CoroutineScope.launch
		delay(1000.seconds)
	}
	delay(1.seconds)
	job.cancel()
}
```

Is this how you are supposed to make a cancellable coroutine?

**Comment by Shynixn** [comment]
1. Q: Is "Coroutine has been cancelled." an error message? How should one avoid it?

No, because it is logged as an INFO message. It is intended to give feedback if a coroutine was cancelled. All cancellations in Kotlin Coroutine trigger a [CancellationException](https://kotlinlang.org/docs/exception-handling.html#cancellation-and-exceptions). Swallowing exceptions without giving feedback would be bad practise.

2. Is this how you are supposed to make a cancellable coroutine?

 ``CoroutineScope.launch`` or even ``plugin.scope.launch`` run directly in the Coroutines Core. ``plugin.launch`` run on an additional coroutine scope layer which catches any exception and logs it to the bukkit logger. In my opinion, this was fine for most cases but to really have organized exception handling according to the [guide](https://kotlinlang.org/docs/exception-handling.html), it is neccessarry to refactor the internals of MCCoroutine. I have been prototyping a bit and will release a major version sometime in the future. 

3. Regarding your two examples:

```kt
val job = launch { // Plugin.launch
	delay(1000.seconds)
}
launch { // Plugin.launch
	delay(1.seconds)
	job.cancel()
}
```

As I mentioned before ``plugin.launch`` prints [uncaught exceptions](https://kotlinlang.org/docs/exception-handling.html#cancellation-and-exceptions).

```kt
launch { // Plugin.launch
	val job = launch { // CoroutineScope.launch
		delay(1000.seconds)
	}
	delay(1.seconds)
	job.cancel()
}
```

The ``job.cancel()`` call still causes an exception but there is no exception handler. You can handle the exception by awaiting the result of the job:


```kt
launch { // Plugin.launch
	val job = launch { // CoroutineScope.launch
             try {
                  delay(1000.seconds)
            }(e : CancellationException){
                println("Job is cancelled")
            }	
	}
	delay(1.seconds)
	job.cancel()
        job.join()  // ... to see the print message      
}
```

In the end you are free to create cancelable coroutines in both ways and they are both perfectly fine. An exception handling rework as mentioned in #52, is going to make sure Coroutines behave exactly like the official guide https://kotlinlang.org/docs/exception-handling.html.

**Comment by nathanfranke** [comment]
Thanks!

**Comment by nathanfranke** [comment]
I have two things to add:

1. 
    > All cancellations in Kotlin Coroutine trigger a [CancellationException](https://kotlinlang.org/docs/exception-handling.html#cancellation-and-exceptions). Swallowing exceptions without giving feedback would be bad practise.

    The documentation of CancellationException states:

    > It is not printed to console/log by default uncaught exception handler. See CoroutineExceptionHandler

    So honestly, I don't think it makes sense to print in the MCCoroutine handler.

2.
    Apologies if this is just me misunderstanding coroutines, but why does this still print `Coroutine has been cancelled.`?
    ```
    val job = plugin.launch {
    	try {
    		awaitCancellation()
    	} catch (_: CancellationException) {
    	}
    }
    job.cancel()
    ```

**Comment by Shynixn** [comment]
I am not sure, might be a bug. Custom logging will be a thing in the future.
